module.exports = {
  ENVIRONMENT: process.env.NODE_ENV || "development",
  SERVICE_NAME: "pp",
  LOG_LEVEL: process.env.LOG_LEVEL || "info",
  PORT: Number(process.env.PORT) || 4057,
  POSTGRES_HOSTNAME: process.env.POSTGRES_HOSTNAME || "127.0.0.1",
  POSTGRES_USERNAME: process.env.POSTGRES_USERNAME,
  POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD || "",
  POSTGRES_PORT: Number(process.env.POSTGRES_PORT) || 5432,
  POSTGRES_DATABASE: process.env.POSTGRES_DATABASE || "postgres",
  IG_PAGE_TOKEN: process.env.IG_PAGE_TOKEN,
  IG_USER_ID: process.env.IG_USER_ID,
  META_GRAPH_BASE_URL: process.env.META_GRAPH_BASE_URL || "https://graph.facebook.com/v21.0",
  API_TOKEN: process.env.API_TOKEN,
  STORAGE_DIR: process.env.STORAGE_DIR || "storage",
  SYNC_INTERVAL_MS: Number(process.env.SYNC_INTERVAL_MS) || 3 * 60 * 60 * 1000,
  QUEUE_POLL_MS: Number(process.env.QUEUE_POLL_MS) || 2000,
  QUEUE_URL: process.env.QUEUE_URL,
  region: process.env.region || "us-east-1",
  accessKeyId: process.env.accessKeyId,
  secretAccessKey: process.env.secretAccessKey,
};
